name: example
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # import the interface only
  analytics:
    path: packages/analytics

  cupertino_icons: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0

flutter:
  uses-material-design: true

# entry point for "flavored_packages" CLI tool
# Register your flavors here
flavored_packages:
  analytics:
    flavors:
      free: "analytics_a"
      paid: "analytics_b"
