name: flavored_packages
description: A tool that let's you register different packages implemention based on flavor
version: 0.0.2
homepage: https://github.com/spideythewebhead/flavored_packages

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  path: ^1.8.1
  yaml: ^3.1.1
  args: ^2.3.1

dev_dependencies:
  lints: 2.0.0
  test: 1.16.0
